const KEY='plate.web.v2';
const seed={setup:false,theme:'light',goals:'',likes:'',avoid:'',allergies:'',meals:[]};
let state=JSON.parse(localStorage.getItem(KEY)||'null')||seed;
let view='home';
const $=s=>document.querySelector(s);
const app=document.getElementById('app');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){localStorage.setItem(KEY,JSON.stringify(state));document.body.classList.toggle('dark',state.theme==='dark')}
const foods=[
['Apple','1 medium (182g)',95,0.5,25,0.3,4],['Banana','1 medium (118g)',105,1.3,27,0.4,3.1],['Orange','1 medium (131g)',62,1.2,15.4,0.2,3.1],['Strawberries','1 cup (152g)',49,1,11.7,0.5,3],['Blueberries','1 cup (148g)',84,1.1,21.4,0.5,3.6],['Avocado','1/2 medium (100g)',160,2,8.5,14.7,6.7],
['Chicken breast, cooked','4 oz (113g)',187,35,0,4,0],['Ground beef, cooked 90% lean','4 oz (113g)',227,30,0,11,0],['Turkey breast, deli','3 oz (85g)',90,15,3,2,0],['Salmon, cooked','4 oz (113g)',233,25,0,14,0],['Tuna, canned in water','1 can drained (142g)',132,29,0,1.2,0],['Egg, large','1 large (50g)',72,6.3,0.4,4.8,0],['Bacon, cooked','2 slices (16g)',86,6,0.6,6.5,0],['Sausage, pork','2 links (50g)',160,7,2,14,0],
['White rice, cooked','1 cup (158g)',205,4.3,44.5,0.4,0.6],['Brown rice, cooked','1 cup (195g)',216,5,44.8,1.8,3.5],['Pasta, cooked','1 cup (140g)',221,8.1,43.2,1.3,2.5],['Oatmeal, cooked','1 cup (234g)',158,5.9,27.3,3.2,4],['White bread','2 slices (56g)',148,5,28,2,1.6],['Whole wheat bread','2 slices (56g)',138,7,23,2.3,3.8],['Tortilla, flour','1 medium (49g)',140,4,24,4,1],['Potato, baked','1 medium (173g)',161,4.3,36.6,0.2,3.8],['French fries','1 medium serving (117g)',365,4,48,17,4],
['Broccoli, cooked','1 cup (156g)',55,3.7,11.2,0.6,5.1],['Carrots, raw','1 cup (128g)',52,1.2,12.3,0.3,3.6],['Green beans, cooked','1 cup (125g)',44,2.4,10,0.3,4],['Spinach, raw','2 cups (60g)',14,1.7,2.2,0.2,1.3],['Mixed salad greens','2 cups (85g)',20,2,3,0.3,2],['Corn, cooked','1 cup (154g)',134,5,29,2.1,4.2],
['Cheddar cheese','1 oz (28g)',113,7,0.4,9.3,0],['Mozzarella cheese','1 oz (28g)',85,6.3,0.6,6.3,0],['Greek yogurt, plain','1 cup (227g)',133,23,9,0.7,0],['Milk, 2%','1 cup (244g)',122,8,12,4.8,0],['Peanut butter','2 tbsp (32g)',188,7.7,6.9,16,1.9],
['Pizza, cheese','2 slices (200g)',560,24,68,22,4],['Pizza, pepperoni','2 slices (218g)',620,27,62,29,4],['Hamburger with bun','1 burger',520,28,40,28,2],['Chicken sandwich','1 sandwich',430,28,39,19,3],['Tacos, beef','2 tacos',340,18,30,18,4],['Macaroni and cheese','1 cup (215g)',350,13,42,15,2],['Chicken nuggets','6 pieces (96g)',270,15,16,17,1],['Grilled cheese sandwich','1 sandwich',380,16,33,21,2],
['Granola','1/2 cup (60g)',270,6,39,11,4],['Cereal, corn flakes','1 cup (25g)',93,2,21,0.2,1],['Protein bar','1 bar',200,20,23,7,5],['Chips, potato','1 oz (28g)',152,2,15,10,1],['Popcorn, air-popped','3 cups (24g)',93,3,19,1.1,3.5],['Cookie, chocolate chip','1 large',160,2,22,8,1],['Ice cream, vanilla','1/2 cup (66g)',137,2.3,16,7.3,0.5],['Chocolate, milk','1 oz (28g)',150,2,17,8,1],
['Water','16 oz',0,0,0,0,0],['Orange juice','1 cup (248g)',112,1.7,25.8,0.5,0.5],['Soda, cola','12 fl oz',140,0,39,0,0]
].map((x,i)=>({id:i+1,name:x[0],serving:x[1],calories:x[2],protein:x[3],carbs:x[4],fat:x[5],fiber:x[6]}));
function nutritionFor(food,mult=1){return {calories:Math.round(food.calories*mult),protein:+(food.protein*mult).toFixed(1),carbs:+(food.carbs*mult).toFixed(1),fat:+(food.fat*mult).toFixed(1),fiber:+(food.fiber*mult).toFixed(1)}}
function render(){save();state.setup?renderApp():renderSetup()}
function renderSetup(){app.innerHTML=`<div class="setup"><div class="setup-box"><div class="eyebrow">welcome to</div><h1 class="title big">plate.</h1><p class="muted">A simple place to understand and keep track of your meals.</p><div class="card"><h2>Choose your look</h2><div class="choices"><button class="choice ${state.theme==='light'?'selected':''}" onclick="state.theme='light';render()">☀️<br><b>Light</b></button><button class="choice ${state.theme==='dark'?'selected':''}" onclick="state.theme='dark';render()">◐<br><b>Dark</b></button></div><div class="field"><div class="label">What are your goals?</div><input id="goals" value="${esc(state.goals)}" placeholder="e.g. learn more about my meals"></div><div class="field"><div class="label">Foods you like</div><input id="likes" value="${esc(state.likes)}" placeholder="e.g. chicken, pasta, fruit"></div><div class="field"><div class="label">Foods you avoid or don't like</div><input id="avoid" value="${esc(state.avoid)}" placeholder="optional"></div><div class="field"><div class="label">Allergies / dietary notes</div><input id="allergies" value="${esc(state.allergies)}" placeholder="optional"></div><button class="btn primary wide" onclick="finishSetup()">Continue</button></div></div></div>`}
function finishSetup(){state.goals=$('#goals').value;state.likes=$('#likes').value;state.avoid=$('#avoid').value;state.allergies=$('#allergies').value;state.setup=true;render()}
function renderApp(){app.innerHTML=`<div class="shell"><aside class="side"><div class="brand">plate.</div><nav class="nav">${[['home','⌂','Home'],['history','◷','History'],['profile','○','Profile']].map(x=>`<button class="${view===x[0]?'active':''}" onclick="view='${x[0]}';render()">${x[1]} <span>${x[2]}</span></button>`).join('')}</nav></aside><main>${view==='home'?home():view==='history'?history():profile()}</main></div>`}
function todayMeals(){const d=new Date();return state.meals.filter(m=>{const x=new Date(m.date);return x.getFullYear()===d.getFullYear()&&x.getMonth()===d.getMonth()&&x.getDate()===d.getDate()})}
function home(){const today=todayMeals(),tot=today.reduce((a,m)=>{a.cal+=m.calories||0;a.pro+=m.protein||0;a.fib+=m.fiber||0;return a},{cal:0,pro:0,fib:0});return `<div class="top"><div><div class="eyebrow">today</div><h1 class="title">Your meals</h1></div><button class="btn" onclick="view='profile';render()">Settings</button></div><div class="grid"><section><div class="card"><h2>Today's overview</h2><div class="stats"><div class="stat"><b>${tot.cal||'—'}</b><span>estimated kcal</span></div><div class="stat"><b>${tot.pro?Math.round(tot.pro):'—'}</b><span>protein g</span></div><div class="stat"><b>${tot.fib?Math.round(tot.fib):'—'}</b><span>fiber g</span></div></div></div><div class="card section"><div class="section-head"><h2>Meals</h2><button class="textbtn" onclick="openFoodLog()">+ Add</button></div>${today.length?today.map(mealCard).join(''):`<div class="empty">Nothing logged yet.<br>Start with a photo or search the food library.</div>`}</div></section><aside><div class="card"><h2>Add a meal</h2><div class="actions"><button class="btn primary" onclick="openScan()">📷 Scan meal</button><button class="btn" onclick="openFoodLog()">⌕ Search food</button></div><button class="btn fullbtn" onclick="openText()">✎ Describe what you ate</button><p class="muted tiny">Photo estimates are always editable. Nutrition comes from the built-in demo food library.</p></div><div class="card section"><h2>Your setup</h2><p class="muted tiny">${esc(state.goals||'No goal added yet.')}</p></div></aside></div>`}
function mealCard(m){return `<div class="meal"><div><b>${esc(m.title)}</b><br><small>${new Date(m.date).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})} · ${m.foods?.map(f=>esc(f.name)).join(', ')||''}</small></div><div><span class="pill">${m.calories!=null?m.calories+' kcal':'estimate pending'}</span></div></div>`}
function history(){let groups={};[...state.meals].sort((a,b)=>new Date(b.date)-new Date(a.date)).forEach(m=>(groups[new Date(m.date).toDateString()]??=[]).push(m));return `<div class="top"><div><div class="eyebrow">history</div><h1 class="title">Your meals</h1></div><button class="btn primary" onclick="openFoodLog()">+ Add</button></div>${Object.keys(groups).length?Object.entries(groups).map(([d,ms])=>`<div class="card section"><h2>${d}</h2>${ms.map(mealCard).join('')}</div>`).join(''):`<div class="card empty">Your meal history will appear here.</div>`}`}
function profile(){return `<div class="top"><div><div class="eyebrow">profile</div><h1 class="title">Your preferences</h1></div></div><div class="card">${[['goals','Goals'],['likes','Foods you like'],['avoid','Foods you avoid'],['allergies','Allergies / dietary notes']].map(x=>`<div class="field"><div class="label">${x[1]}</div><input id="p_${x[0]}" value="${esc(state[x[0]])}"></div>`).join('')}<div class="field"><div class="label">Theme</div><select id="p_theme"><option value="light" ${state.theme==='light'?'selected':''}>Light</option><option value="dark" ${state.theme==='dark'?'selected':''}>Dark</option></select></div><button class="btn primary" onclick="saveProfile()">Save changes</button><button class="btn" style="margin-left:8px" onclick="state.setup=false;render()">Reset setup</button><div class="source-note"><b>Food library</b><br>Demo foods are stored locally so GitHub Pages works with no API key. The structure is ready to swap in USDA FoodData Central later. USDA provides an API and downloadable food data for developers. <a href="https://fdc.nal.usda.gov/" target="_blank" rel="noreferrer">FoodData Central</a>.</div></div>`}
function saveProfile(){['goals','likes','avoid','allergies'].forEach(k=>state[k]=$('#p_'+k).value);state.theme=$('#p_theme').value;render()}
function modal(inner){closeModal();const x=document.createElement('div');x.className='backdrop';x.id='modal';x.innerHTML=`<div class="modal">${inner}</div>`;document.body.appendChild(x)}
function closeModal(){document.getElementById('modal')?.remove()}
function openFoodLog(){modal(`<div class="modal-head"><div><div class="eyebrow">food library</div><h2>Add food</h2></div><button class="iconbtn" onclick="closeModal()">×</button></div><p class="muted">Search common foods, choose a serving, and add it to a meal.</p><div class="field"><input id="foodsearch" autofocus placeholder="Search chicken, rice, pizza, apple..." oninput="renderFoodResults()"></div><div class="mealtype"><label>Meal <select id="mealtype"><option>Breakfast</option><option>Lunch</option><option>Dinner</option><option>Snack</option></select></label></div><div id="foodresults" class="results"></div><div class="selectedbar" id="selectedbar">No foods selected yet.</div><button class="btn primary wide" onclick="openSelectedEditor()">Review meal</button></div>`);renderFoodResults()}
function renderFoodResults(){const q=($('#foodsearch')?.value||'').toLowerCase().trim();const results=foods.filter(f=>!q||(`${f.name} ${f.serving}`).toLowerCase().includes(q)).slice(0,18);const el=$('#foodresults');if(!el)return;el.innerHTML=results.map(f=>`<button class="result" onclick="addSelected(${f.id})"><span><b>${esc(f.name)}</b><small>${esc(f.serving)}</small></span><strong>${f.calories} kcal</strong></button>`).join('')||`<div class="empty small">No match in the demo library. Try a simpler search.</div>`}
let selectedFoods=[];
function addSelected(id){const f=foods.find(x=>x.id===id);if(!f)return;selectedFoods.push({...f,qty:1});updateSelectedBar();}
function updateSelectedBar(){const el=$('#selectedbar');if(el)el.innerHTML=selectedFoods.length?selectedFoods.map((f,i)=>`<span class="sel">${esc(f.name)} × ${f.qty}<button onclick="selectedFoods.splice(${i},1);updateSelectedBar()">×</button></span>`).join(''):'No foods selected yet.'}
function openSelectedEditor(){if(!selectedFoods.length){return}const meal=selectedFoods.reduce((a,f)=>{const n=nutritionFor(f,f.qty);a.calories+=n.calories;a.protein+=n.protein;a.carbs+=n.carbs;a.fat+=n.fat;a.fiber+=n.fiber;return a},{calories:0,protein:0,carbs:0,fat:0,fiber:0});const type=$('#mealtype')?.value||'Meal';showEditor({title:type,foods:selectedFoods.map(f=>({...f,amount:f.serving})),...meal,note:'Estimates are based on the selected serving sizes. Review before saving.'});selectedFoods=[]}
function openText(){modal(`<div class="modal-head"><div><div class="eyebrow">quick log</div><h2>Describe what you ate</h2></div><button class="iconbtn" onclick="closeModal()">×</button></div><p class="muted">For the demo, plate. matches simple food names against its local library. You can edit the result before saving.</p><textarea id="foodtext" rows="4" placeholder="e.g. 2 eggs, toast, and a banana"></textarea><div class="field"><label class="label">Meal <select id="textmeal"><option>Breakfast</option><option>Lunch</option><option>Dinner</option><option>Snack</option></select></label></div><div class="modal-actions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="estimateText()">Find foods</button></div></div>`)}
function estimateText(){const text=$('#foodtext').value.trim();if(!text)return;const parts=text.split(/,|\band\b|\+/i).map(x=>x.trim()).filter(Boolean);const matches=[];parts.forEach(p=>{const clean=p.replace(/^\d+(\.\d+)?\s*(x|×)?\s*/i,'').trim();const found=foods.find(f=>clean.toLowerCase().includes(f.name.toLowerCase())||f.name.toLowerCase().includes(clean.toLowerCase()));if(found)matches.push({...found,qty:1,amount:found.serving});else matches.push({name:clean,serving:'1 serving',calories:null,protein:null,carbs:null,fat:null,fiber:null,qty:1})});const type=$('#textmeal').value;const known=matches.filter(f=>f.calories!=null);const total=known.reduce((a,f)=>{const n=nutritionFor(f,f.qty);Object.keys(n).forEach(k=>a[k]=(a[k]||0)+n[k]);return a},{calories:0,protein:0,carbs:0,fat:0,fiber:0});showEditor({title:type,foods:matches,...total,note:matches.some(f=>f.calories==null)?'Some foods were not found in the demo library. Add the missing nutrition values before saving.':'Matched against the local demo food library.'})}
function openScan(){modal(`<div class="modal-head"><div><div class="eyebrow">photo</div><h2>Scan a meal</h2></div><button class="iconbtn" onclick="closeModal()">×</button></div><p class="muted">Choose a meal photo. This demo does not send photos anywhere. It creates a review draft so the photo workflow is ready for a free/local vision model later.</p><input id="photo" type="file" accept="image/*" capture="environment"><img id="preview" class="preview hidden" alt="Meal preview"><div class="modal-actions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="scanDraft()">Create draft</button></div></div>`);$('#photo').onchange=e=>{const f=e.target.files[0];if(f){const im=$('#preview');im.src=URL.createObjectURL(f);im.classList.remove('hidden')}}}
function scanDraft(){showEditor({title:'Photo meal',foods:[{name:'Food item — review',amount:'1 serving',calories:null,protein:null,carbs:null,fat:null,fiber:null}],calories:0,protein:0,carbs:0,fat:0,fiber:0,note:'Photo recognition is a plug-in point. No image leaves this demo, and every estimate is editable.'})}
function foodRow(f,i){return `<div class="foodrow" data-row="${i}"><div><div class="label">Food</div><input class="fn" value="${esc(f.name)}"></div><div><div class="label">Amount</div><input class="fa" value="${esc(f.amount||f.serving||'1 serving')}"></div><div><div class="label">kcal</div><input class="fc" type="number" min="0" value="${f.calories??''}"></div><button class="btn danger" onclick="this.closest('.foodrow').remove();recalcEditor()">×</button></div>`}
function showEditor(m){modal(`<div class="modal-head"><div><div class="eyebrow">review</div><h2>Review meal</h2></div><button class="iconbtn" onclick="closeModal()">×</button></div><p class="muted">Change portions or nutrition values before saving.</p><div class="field"><div class="label">Meal name</div><input id="mtitle" value="${esc(m.title)}"></div><div id="foods">${m.foods.map(foodRow).join('')}</div><button class="btn" onclick="addFood()">+ Add food</button><div class="stats editorstats"><div class="stat"><span>Calories</span><input id="mcal" type="number" min="0" value="${m.calories??''}"></div><div class="stat"><span>Protein g</span><input id="mpro" type="number" min="0" value="${m.protein??''}"></div><div class="stat"><span>Carbs g</span><input id="mcarb" type="number" min="0" value="${m.carbs??''}"></div><div class="stat"><span>Fat g</span><input id="mfat" type="number" min="0" value="${m.fat??''}"></div><div class="stat"><span>Fiber g</span><input id="mfib" type="number" min="0" value="${m.fiber??''}"></div></div><div class="field"><div class="label">Nutrition note</div><textarea id="mnote" rows="3">${esc(m.note||'')}</textarea></div><div class="modal-actions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveMeal()">Save meal</button></div></div>`)}
function addFood(){const n=document.querySelectorAll('.foodrow').length;$('#foods').insertAdjacentHTML('beforeend',foodRow({name:'New food',amount:'1 serving',calories:null},n))}
function recalcEditor(){const rows=[...document.querySelectorAll('.foodrow')];const cal=rows.reduce((a,r)=>a+(parseFloat(r.querySelector('.fc').value)||0),0);$('#mcal').value=Math.round(cal)}
function saveMeal(){const rows=[...document.querySelectorAll('.foodrow')];const foodsOut=rows.map(r=>({name:r.querySelector('.fn').value.trim()||'Food',amount:r.querySelector('.fa').value.trim()||'1 serving',calories:r.querySelector('.fc').value?+r.querySelector('.fc').value:null,protein:null,carbs:null,fat:null,fiber:null}));const meal={id:(crypto.randomUUID?crypto.randomUUID():String(Date.now())),date:new Date().toISOString(),title:$('#mtitle').value.trim()||'Meal',foods:foodsOut,calories:$('#mcal').value?+$('#mcal').value:null,protein:$('#mpro').value?+$('#mpro').value:null,carbs:$('#mcarb').value?+$('#mcarb').value:null,fat:$('#mfat').value?+$('#mfat').value:null,fiber:$('#mfib').value?+$('#mfib').value:null,note:$('#mnote').value};state.meals.push(meal);closeModal();view='home';render()}
render();
